name: Build the RPM
on: [push]
jobs:
  build-rpm:
    container: rpmbuild/centos7
      volumes: 
        - /data/
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: sudo git clone https://github.com/aws/efs-utils.git 
        working-directory: /data
