name: Build the RPM
on: [push]
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: rpmbuild/centos7
    steps:
      - run: git clone https://github.com/aws/efs-utils
        working-directory: /tmp
      - run: make rpm
        working-directory: /tmp/efs-utils
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: /tmp/efs-utils/build/amazon-efs-utils-1.33.1-1.el7.centos.noarch.rpm
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release text"
  
