name: Build the RPM
on: [push]
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install git rpm make -y
      - run: git clone https://github.com/aws/efs-utils.git 
      - run: cd efs-utils
      - run: make rpm

