name: Build the RPM
on: [push]
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: rpmbuild/centos7
    steps:
      - run: git clone https://github.com/aws/efs-utils
        working-directory: /tmp
      - run: make rpm
        working-directory: /tmp/efs-utils

