name: Build the RPM
on: [push]
jobs:
  build-rpm:
    runs-on: ubuntu-latest
    container: 
      image: rpmbuild/centos7
      volumes: 
        - /data/
    steps:
      - run: uname -a
        working-directory: /data
