name: Build the RPM
on: [push]
jobs:
  build-rpm:
    container: 
      image: rpmbuild/centos7
      volumes: 
        - /data/
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - run: uname -a
        working-directory: /data
